# Generated by Django 5.0 on 2024-01-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('github_link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'All Projects',
            },
        ),
    ]
