# Generated by Django 5.0 on 2024-01-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_allprojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allprojects',
            old_name='description',
            new_name='title',
        ),
    ]
