# Generated by Django 5.0 on 2024-01-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_description_allprojects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='description',
            field=models.CharField(blank=True, default='Your default description here', max_length=200),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
