# Generated by Django 5.0 on 2024-01-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_allprojects_description_alter_allprojects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='description',
            field=models.CharField(blank=True, default='Project description here', max_length=200),
        ),
    ]
