# Generated by Django 5.0 on 2024-01-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_allprojects_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProjects',
            new_name='AllProject',
        ),
    ]
