# Generated by Django 5.0 on 2024-01-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_allprojects_delete_allprojectsdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProjects',
        ),
    ]
