# Generated by Django 5.0 on 2024-01-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_allprojects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='description',
            field=models.CharField(blank=True, default='Project description here', max_length=1000),
        ),
    ]
